### PR TITLE
fix encoding issue with nested object->dictionary translations

### PR DESCRIPTION
**Pull request by dwb357**
Fix an issue that resulted in the top level object->dictionary translation being lost.

### CODE REVIEW

**Comment by hkellaway** [comment]
@dwb357 this failed on the `testEncodeEncodableDictionary ` test (tests can be found in the `GlossExample` project currently. can you fix the test to pass?

**Comment by dwb357** [comment]
I'll take a look at it this afternoon.

David

**Comment by dwb357** [comment]
Should be gtg now.

**Comment by hkellaway** [comment]
thanks @dwb357

**Pull request merged**
