### PR TITLE
Updated Use "Legacy Swift Version" for targets

### PR DESCRIPTION
**Pull request by aventurella**
specifically:

- macOS
- tvOS
- watchOS

### CODE REVIEW

**Comment by hkellaway** [comment]
@aventurella can you explain what this does?

**Comment by aventurella** [comment]
it tells the compiler to use swift 3

**Comment by aventurella** [comment]
Xcode throws a compile time warning when it's left at undecided

**Comment by aventurella** [comment]
Just for a reference, here's the error Xcode 8 Beta 4 throws up:

gloss_xcodeproj

**Pull request merged**
