### PR TITLE
Moved tests from GlossExample to Gloss

### PR DESCRIPTION
**Pull request by RahulKatariya**
It would be better if you keep the tests in the Gloss framework project itself rather than the Example Project.

### CODE REVIEW

**Comment by hkellaway** [comment]
why is it better in the framework project would you say?

**Comment by RahulKatariya** [comment]
Every time you make a change in Gloss and write a test case. To check the functionality you need to open Example Project and run the tests. 

Ideally it should be contained in Gloss because we are testing the framework itself. 

When i made the first pull request i thought this library doesn't contain any test cases because everyone writes the test cases in the framework itself.

Any thoughts ?

**Comment by hkellaway** [comment]
fair enough, i don't have a case for keeping it with the example project; i had them there because i use the example project when i work on development

**Comment by RahulKatariya** [comment]
You may discard it if its easier for you that way.

**Comment by hkellaway** [comment]
it'd be easiest to recreate this once the release is stable.

**Pull request closed without merging**
