### PR TITLE
Initial Linux support

### PR DESCRIPTION
**Pull request by rbukovansky**
The third time's lucky? Hopefully...

This have been tried to build on Ubuntu 16.10 with Swift versions:
3.0.1
3.0.2
DEVELOPMENT SNAPSHOT 2016-12-14

and successfully passed all tests.

### CODE REVIEW

**Comment by rbukovansky** [comment]
@hkellaway Do we really need all those `([)(U)Int32(])`, `([)U(Int64)(])` encoders and decoders? Asking for friend...

**Comment by hkellaway** [comment]
is there a reason not to have them besides the failing Linux tests..?

**Comment by rbukovansky** [comment]
Well, is there anybody insane who uses Int32 or UInt64 directly in code instead of Int/UInt? :smirk: 
I just hope not...

BTW The build using the new `.travis.yml` file which uses swift toolchain, instead of Xcode, fails too for macOS on ([)UInt64(])... :roll_eyes:

**Comment by rbukovansky** [comment]
And of course, directly on my girlfriend's Mac it builds normally without problem...

Why me?

**Comment by hkellaway** [comment]
someone uses them https://github.com/hkellaway/Gloss/pull/168

**Comment by rbukovansky** [comment]
I see... Madness, but OK. Thanks.

**Comment by rbukovansky** [comment]
@hkellaway 
1. So I have reverted back to using `NSNumber`. I've tried to get all the code to use "natural" types, because NSNumber doesn't work for those size-specific Ints and UInts on Linux, but I have failed. 😢
2. That means, Gloss wouldn't be able to support `([)(U)Int32(]) & ([)(U)Int64(])` on Linux. There is something fundamentally broken in Swift or Foundation library on Linux, so I have "removed" tests for these on Linux and added remark to README file.
3. If you accept this PR, please squash the commits (you can do it directly here within this PR, Github will make squashed merge commit to your `develop` branch) and leave there this commit message:
`Initial Linux support`. (Or do you want me to redo this?)
4. I will monitor future developments of Swift and will try to move to those mentioned "natural" types again when Swift/Foundation is fine again on Linux.

Thank you. For this library and your patience.

**Comment by hkellaway** [comment]
@rbukovansky thanks for your work on this! apologies its taken me a while to get back around to it.

one stipulation i have about this is - i'm not at all familiar with Linux and cannot personally provide a guarantee from version to version that Linux won't break. can i hold you accountable for fixing issues if raised by Linux users? otherwise i cannot with good conscience offer Linux support.

**Comment by hkellaway** [comment]
regarding squashing - would you mind doing so ?

**Comment by rbukovansky** [comment]
@hkellaway 1. Time - that's OK. We all had holidays... ;)

2. Support for Linux: Yes, I will take care of it. No worries...
Gloss is IMHO the best JSON library for Swift and I'm happy it can be used on Linux.

Ad squashing those commits: I will take care of it, no worries here either.

**Comment by rbukovansky** [comment]
@hkellaway OK, I have squashed those commits, but the Travis build fails and it's not fault of the new code... 😩 Could you please try force the rebuild of this PR directly on Travis CI? It passed on my Travis CI https://travis-ci.org/rbukovansky/Gloss/builds/189431942

Thanks.

**Comment by rbukovansky** [comment]
@hkellaway To get this all going I will need you to accept #258 #250 and then this PR... Then we will have Linux support in Gloss and tests of any new code for both platforms (OS X and Linux) on Travis CI.

I have merged all those three PRs to one branch in my repo and it builds OK https://travis-ci.org/rbukovansky/Gloss/builds/189439692 to prove it.

Thank you.

**Comment by rbukovansky** [comment]
@hkellaway Rebased on top of `develop` branch. #250 needs to be merged first.

Test build of both PRs merged is here: https://travis-ci.org/rbukovansky/Gloss/builds/192286539

**Comment by rbukovansky** [comment]
@hkellaway Thanks. Hooray, another Mt. Everest conquered! 😉

**Comment by hkellaway** [comment]
🎉

**Comment by hkellaway** [comment]
hello @rbukovansky - i didn't have your email but wanted to put you in touch with another developer who would like to help support Gloss on Linux: @crspybits

i'm going to add you both as Collaborators so i can tag you on Linux issues; i'd leave it to you two to communicate on who had the bandwidth to address the Issue. despite being Collaborators, i ask that you make pull requests (only against the `linux` branch) - and i'll be the one to make a final review and merge.

if you're okay with sharing your email - please email me at hello@harlankellaway.com so i can put you in touch with @crspybits that way

**Comment by rbukovansky** [comment]
@hkellaway Reply over e-mail sent. And it's good I'm not alone in this effort. Hooray to @crspybits!

**Pull request merged**
