### PR TITLE
XCode 11 SPM support

### PR DESCRIPTION
**Pull request by urosk**
Updated package definition and project structure to allow direct importing via XCode 11 SPM.
- Package manifest created with Swift Tools 5.1
- Moved files around to comply with default folder structure for SPM

### CODE REVIEW

**Comment by hkellaway** [comment]
hi @urosk ! thank you so much for contributing

what's a good way to verify this? i'm not super familiar with SPM

**Comment by urosk** [comment]
Hi!
Test this by:
1.) Open XCode 11
2.) Open the project file
3.) Click packages tab
4.) Click + to add a package 
5.) Pick Gloss (note: it has to be favorited on the GitHub account you use in XCode)
6.) Enter "XCode_11_SPM" in the branch field

The package should be correctly resolved, and added to XCode. Importing Gloss should work. Tests should run.

Keep in mind though, that I totally rearranged the files in folders. I'm not sure if any other supported package managers expect a fixed folder structure. If yes, we could also try to preserve the old structure by specifying a custom SPM path.

**Comment by hkellaway** [comment]
this is awesome - thanks for doing that (and for teaching me a bit about Swift PM!)

i'll work on a `3.1.0` release this week - til then, you can point to `develop`

**Comment by hkellaway** [comment]
Gloss `3.1.0` has been released with support for SPM! 🎉

**Pull request merged**
