### PR TITLE
Linux and SwiftPM Support

### PR DESCRIPTION
**Pull request by rbukovansky**
This should be successor of #229, a final version of support for Linux and SwiftPM(on Linux).

It builds and passes all tests on my Ubuntu 16.10 with these versions of Swift:
```
3.0.1
3.0.2
DEVELOPMENT SNAPSHOT 2016-12-14
```

Woof.

### CODE REVIEW

**Comment by rbukovansky** [comment]
@hkellaway I have absolutely no idea why that build on Travis CI failed. Could you please take a look and let me know? Thank you.

BTW Could we please get Travis CI to try build Gloss on Linux as well? Thanks.

**Comment by hkellaway** [comment]
@rbukovansky im not familiar with Linux in the least; not sure how to get Travis CI to build Gloss on Linux as well

**Comment by hkellaway** [comment]
@rbukovansky this PR seems to include changes already in `develop` not made by you (e.g. update to the CHANGELOG and podspec) - i'm having trouble telling what changes are specific to you. is there a way to remove any changes that weren't made by you?

**Comment by hkellaway** [comment]
```Executed 170 tests, with 5 failures (0 unexpected) in 0.188 (0.364) seconds
Failing tests:
	-[DecoderTests testDecodeUInt64()]
	-[DecoderTests testDecodeUInt64Array()]
	-[FlowObjectCreationTests testObjectDecodedFromJSONHasCorrectProperties()]
	-[FlowObjectCreationTests testObjectDecodedFromJSONHasCorrectProperties()]
	-[OperatorTests testDecodeOperatorUInt64ArrayReturnsDecoderUInt64Array()]```

**Comment by rbukovansky** [comment]
Yeah, I will rework this... 🙄 Sorry!

And will take a look on that Travis guy as well... Thanks.

**Comment by hkellaway** [comment]
no problem! i appreciate the effort

**Pull request closed without merging**
