### PR TITLE
Migrate to Xcode 9 & Swift 4

### PR DESCRIPTION
**Pull request by ryanbaldwin**
Very few changes. All warnings removed; tests pass; life is sweet.

### CODE REVIEW

**Comment by hkellaway** [comment]
Travis hasn't completed yet, but i'm guessing it might fail - probably need to update `.travis.yml` to use `xcode9`, perhaps `OS=11.0`

**Comment by andrewjmeier** [comment]
@hkellaway Are there plans to update to Swift 4 soon?

**Comment by hkellaway** [comment]
@ryanbaldwin can you give updating the Travis file a try per my comment above?

**Comment by hkellaway** [comment]
these changes were included in this PR: https://github.com/hkellaway/Gloss/pull/307

**Pull request closed without merging**
