### PR TITLE
Updating structure to conform Swift and SwiftPM on Linux

### PR DESCRIPTION
**Pull request by rbukovansky**
This is Work In Progress.

There are some failures in code like:
```
Test Case 'DecoderTests.testDecodeInt32' started at 17:08:07.742
/home/rbukovansky/Projects/Gloss/Tests/GlossTests/DecoderTests.swift:421: error: DecoderTests.testDecodeInt32 : XCTAssertTrue failed - Decode Int32 should return correct value
Test Case 'DecoderTests.testDecodeInt32' failed (0.0 seconds).
Test Case 'DecoderTests.testDecodeInt32Array' started at 17:08:07.742
fatal error: unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    libswiftCore.so                    0x00007fa8de581300 swift_reportError + 117
1    libswiftCore.so                    0x00007fa8de592750 _swift_stdlib_reportFatalError + 61
```
and I'm not sure why...

### CODE REVIEW

**Comment by rbukovansky** [comment]
This is officially weird. It passes on Mac, but not on Linux? :eyes:

**Comment by hkellaway** [comment]
the commit messages make this PR appear unfinished. what is the status?

**Comment by rbukovansky** [comment]
As original comment states, it's still work in progress. I have 2 issues on Linux, which I have reported to Swift development team, but they are still not resolved. Sorry.
If you want you can close this PR. I will reopen it when it's resolved. My intentions were to let you know I'm working on this.
Thanks.

**Comment by hkellaway** [comment]
no need to apologize! yes, let's close this for now and reopen or make a new PR once resolved. appreciate the effort

**Pull request closed without merging**
