### PR TITLE
fixed compactMap compile issue

### PR DESCRIPTION
**Pull request by syn-deepakbadiger**

### CODE REVIEW

**Comment by syn-deepakbadiger** [comment]
Not sure, why it failed, though i removed flatMap and converted the code to compactMap and ran a build on my side to ensure it builds fine and with no errors

**Comment by syn-deepakbadiger** [comment]
is there something that i would need to do so as to ensure travis CI builds properly?

**Comment by syn-deepakbadiger** [comment]
screen shot 2018-04-19 at 11 46 29 am
screen shot 2018-04-19 at 11 46 52 am
screen shot 2018-04-19 at 11 47 12 am

as can be seen from the screen shots, Travis is failing on line 82 for "Unresolved Identifier compactMap", but i have already tested that with the build on my side and i don't see any unresolved errors on my side as evident in the code screen shot..

screen shot 2018-04-19 at 11 49 59 am

**Comment by hkellaway** [comment]
can you try updating `.travis.yml` with `osx_image: xcode9.3`

**Comment by syn-deepakbadiger** [comment]
updated the yml file and it went through the CI again. However, unfortunately, it failed this time even without completing the build process.

**Comment by mladen7** [comment]
> yes, `compactMap` is Swift 4.1 you can use Gloss version `2.0.1`

Thanks for the quick reply, think i'll boost the project to latest swift instead :)

**Pull request closed without merging**
