### PR TITLE
Travis CI build on OS X and Linux

### PR DESCRIPTION
**Pull request by rbukovansky**
This should run builds of Gloss on macOS and Linux

### CODE REVIEW

**Comment by rbukovansky** [comment]
This will (should) pass when #249 is merged.

**Comment by hkellaway** [comment]
@rbukovansky shouldn't this succeed on Travis?

**Comment by rbukovansky** [comment]
@hkellaway It should and will when you merge #258, which actually makes that new code compatible with macOS and Linux...

The thing is, with this it won't be running Xcode for build and test with iOS as a target anymore, but directly running `swift` compiler...

**Comment by rbukovansky** [comment]
@hkellaway As I stated here https://github.com/hkellaway/Gloss/pull/249#issuecomment-270860442 the merge of those tree PRs needs to happen to get things going. Please, do so. Thank you!

**Comment by hkellaway** [comment]
will work on testing and merging these this coming weekend. thanks for your patience!

**Comment by rbukovansky** [comment]
That's OK, sounds good to me!

**Comment by rbukovansky** [comment]
@hkellaway Rebased on top of `develop` branch. #249 needs to be merged following merge of this branch.

Test build of both PRs merged is here: https://travis-ci.org/rbukovansky/Gloss/builds/192286539

**Comment by rbukovansky** [comment]
@hkellaway Thanks, now we will know if anybody makes changes that work on Mac, but break on Linux! 😈

**Comment by hkellaway** [comment]
@rbukovansky a couple new tests were added and now the Linux build is breaking - see https://github.com/hkellaway/Gloss/issues/264

i've added you as a Collaborator so that i'm able to tag you in Issues. though it grants you push access, i'd like, for now, to still orchestrate merges and releases - so if you could continue to submit Pull Requests in the same manner as before, that'd be great.

**Comment by hkellaway** [comment]
the branch where this is present is named `linux`

**Comment by rbukovansky** [comment]
@hkellaway No worries, I have no plans for world domination... Well, except for one of my projects... :wink:

**Pull request merged**
