### PR TITLE
CocoaPods cleanup, Carthage compatibility

### PR DESCRIPTION
**Pull request by bojan**
Removed the Example pods from source control.
Also the Example schemes has been un-shared, since it created issues in Carthage.
The git ignore file has been extended with CocoaPods, Carthage and Xcode 7 exclusions.

### CODE REVIEW

**Comment by hkellaway** [comment]
I appreciate the assistance with Carthage, I'm not super familiar. 

Can you tell me the particular need to remove Pods from source control - it's not immediately apparent

**Comment by bojan** [comment]
Since the pods can be recreated using the podfile at anytime, we shouldn't add the Pods directory, only the podfile. It's just good practice to keep your repository cleaner.

**Comment by hkellaway** [comment]
Removing all schemes from the `GlossExample` project leaves it and its test suite unable to be run. Would it mess with Carthage to reintroduce one un-shared scheme on that project ?

**Comment by hkellaway** [comment]
@bojan can you weigh in on this before i merge ^

**Comment by bojan** [comment]
@hkellaway I've manually added the GlossExampleTests target and the test seem to work just fine. Few of them fail, but the target compiles.

**Comment by bojan** [comment]
Also, before I push the new commits, I've noticed that the deployment target of the library is iOS 9.0. No iOS 8 support or is this a mistake?

**Comment by bojan** [comment]
I've updated the readme for a better Carthage integration. Everything should work now.

**Comment by hkellaway** [comment]
Awesome, thanks. Yep, deployment should be 8.0

**Comment by bojan** [comment]
@hkellaway Great :+1: When's 0.5.3 coming?

**Comment by hkellaway** [comment]
latest, Sunday

**Pull request merged**
