### PR TITLE
Add valueForKeyPathCoding

### PR DESCRIPTION
**Pull request by RahulKatariya**
I have not tested this much but this will allow us to use keyPaths when needed.

    struct Person: Glossy {
        
        let id: String?
        let name: String?
        
        // MARK: - Deserialization
        
        init?(json: JSON) {
            self.id = "args.id" <~~ json
            self.name = "args.name" <~~ json
        }
        
        // MARK: - Serialization
        
        func toJSON() -> JSON? {
            return jsonify([
                "args.id" ~~> self.id,
                "args.login" ~~> self.name
                ])
        }
        
    }

### CODE REVIEW

**Comment by RahulKatariya** [comment]
The toJSON() is not working correctly right now. If you are interested in this feature then i can spend more time optimising it and include test cases.

**Comment by hkellaway** [comment]
i'm not quite gathering the utility of this. what is not working about `toJSON()` that this fixes?

**Comment by RahulKatariya** [comment]
Value for key path increases the flexibility. If we have a JSON like below.

    {
        "addressLine" : "",
        "city" : "",
        "state" : "",
        "location": {
            "lat" : 23.0078201,
            "lng" : 88.5428696
        }
    }

then we can skip the Location struct and use location in directory Address object using keyPath

    struct Address: Decodable {

        let addressLine: String?
        let city: String?
        let state: String?
        let latitude: Double?
        let longitude: Double?

        // MARK: - Deserialization

        init?(json: JSON) {
            self.addressLine = "addressLine" <~~ json
            self.city = "city" <~~ json
            self.state = "state" <~~ json
            self.latitude = "location.lat" <~~ json
            self.longitude = "location.lng" <~~ json
        }

    }

This pull request is working fine in Deserialisation but not while converting back to JSON().

**Comment by hkellaway** [comment]
i see. does this work for nested models? e.g. i'd implement the example as below - does decoding still work? what about if i wanted a model with mixed  properties - i.e. some are other `Glossy` models and some are declared in the format you're proposing (e.g. `args.id`).

i do appreciate the thought/work, but i'd not consider it unless it worked for `toJSON()` and the cases mentioned above.

```
struct Person: Glossy {

    let args: Args?

    // MARK: - Deserialization
    init?(json: JSON) {
        self.args = "args" <~~ json
    }

    // MARK: - Serialization

    func toJSON() -> JSON? {
        return jsonify([
            "args" ~~> self.args
            ])
    }

}

struct Args: Glossy {

    let id: String?
    let name: String?

    init?(json: JSON) {
        self.id = "id" <~~ json
        self.name = "name" <~~ json
    }

    func toJSON() -> JSON? {
        return jsonify([
            "args.id" ~~> self.id,
            "args.login" ~~> self.name
            ])
    }
}
```

**Comment by RahulKatariya** [comment]
Hi Harlan,

I have fixed the toJSON() method and have also added the test case which you can see at https://github.com/RahulKatariya/Gloss/blob/glossy-keypath/Sources/GlossTests/KeyPathTests.swift

Best Regards,
Rahul

**Comment by hkellaway** [comment]
great - i'll have to spend some time playing with this myself this weekend; i'll respond back here if i encounter issues

**Comment by RahulKatariya** [comment]
👍🏼

**Comment by hkellaway** [comment]
@RahulKatariya can you rebase this? merge conflicts with the latest `develop`

**Comment by hkellaway** [comment]
@RahulKatariya i rebased and merged this into `develop` outside of this PR - will be available in `0.7.0`. thanks! :tada:

**Comment by RahulKatariya** [comment]
@hkellaway Sorry i was on weekend vacation. I have one more pull request to make which i think could be available in 0.7.0. There is some issue in modelsArrayFromJson.

**Comment by hkellaway** [comment]
no prob. would it be possible to make that today? I have time to review

What is the issue?

**Comment by RahulKatariya** [comment]
I have opened the issue #106

**Comment by hkellaway** [comment]
thanks @RahulKatariya

**Pull request closed without merging**
